import { build } from "esbuild";
import { mkdir, writeFile } from "node:fs/promises";
const result = await build({
	entryPoints: ["browser/auth.ts"],
	bundle: true,
	format: "iife",
	target: "es2022",
	platform: "browser",
	write: false,
	minify: true,
});
await mkdir("src/generated", { recursive: true });
await writeFile(
	"src/generated/auth-client.ts",
	`// Generated by scripts/build-auth.mjs.\nexport default ${JSON.stringify(result.outputFiles[0].text)};\n`,
);
